services:
  db:
    image: mysql:8
    container_name: bees-mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: bees_db
      MYSQL_USER: beekeeper
      MYSQL_PASSWORD: mysql
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
volumes:
  mysql_data:
